In [1]:
import pandas as pd
import numpy as np
import sympy as sy

from evaluation import FileAnswer, Quizz
file_answer = FileAnswer('CURSO', 'Tema1', 'local')
quizz = Quizz('1', 'CURSO', 'Tema1', 'local')

¿Cuál es la derivada de $f(x) = \frac{x^3}{3}$?

### Forma cuadrática

$$ f(\mathbf{x}) = \dfrac{1}{2} \mathbf{x}^T A \mathbf{x} - \mathbf{b}^T \mathbf{x} + c $$

Usando los valores de $A$, $B$ y $C$ calcula la forma de $f(\mathbf{x})$

In [2]:
t = np.linspace(0,1,10)
w = np.sin(t)
opcion = 'c'
derivada = 'x**2'
matriz_np = np.array([[0.10, -1.],[0.30,-1.]] )
array_np = np.array([-200, 20])
flotante = 0.0
entero = 1
complejo = 1 + 5j
logico = True
lista = [0, 1, 3.4]
##tupla = ('a', 'b', 'c')
tupla = (1.2, 3.1416, np.pi)
##diccionario = {1:'k1', 2:'2.0'}
diccionario = {1:1.3, 2:3.14}
conjunto = {4,1,8,0,4,20}

x = sy.Symbol('x')
y = sy.Symbol('y')
A, B, C = matriz_np, array_np, flotante
forma_cuadratica = 0.5 * A[0,0] * x**2 + 0.5 * A[1,1] * y**2 + 0.5 * (A[0,1]+A[1,0])* x * y - B[0] * x - B[1] * y + C

In [3]:
respuestas = [t,w,opcion,derivada,matriz_np,array_np,flotante,entero,complejo,logico,lista,tupla,diccionario,conjunto,forma_cuadratica]
for i in respuestas:
    print(i)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.         0.11088263 0.22039774 0.3271947  0.42995636 0.52741539
 0.6183698  0.70169788 0.77637192 0.84147098]
c
x**2
[[ 0.1 -1. ]
 [ 0.3 -1. ]]
[-200   20]
0.0
1
(1+5j)
True
[0, 1, 3.4]
(1.2, 3.1416, 3.141592653589793)
{1: 1.3, 2: 3.14}
{0, 1, 4, 20, 8}
0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20*y

In [4]:
file_answer.write('1a', t, 'Deberías checar ...')
file_answer.write('1b', w)
file_answer.write('2', opcion, 'Las opciones válidas son ...')
file_answer.write('3', derivada, 'Checa las reglas de derivación')
file_answer.write('4', matriz_np, 'Checa las entradas de la matriz A')
file_answer.write('5', array_np, 'Checa las entradas del vector B')
file_answer.write('6', flotante, 'Checa el valor de flotante')
file_answer.write('7', entero, 'Checa el valor de entero')
file_answer.write('8', complejo, 'Checa el valor de complejo')
file_answer.write('9', logico, 'Checa  logico')
file_answer.write('10', lista, 'Checa la lista')
file_answer.write('11', tupla, 'Checa la tupla')
file_answer.write('12', diccionario, 'Checa la diccionario')
file_answer.write('13', conjunto, 'Checa la conjunto')
file_answer.write('14', str(forma_cuadratica),'Revisa tus operaciones algebráicas para calcular f(x)')
file_answer.to_file('1')

El directorio :/home/jovyan/macti_lib/macti/CURSO/utils/.ans/Tema1/ ya existe
Respuestas y retroalimentación almacenadas.

In [5]:
ans_df2 = pd.read_parquet('../utils/.ans/Tema1/.__ans_1') # Se lee en un DataFrame
ans_df2

,1a,1b,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"[0.0, 0.1111111111111111, 0.2222222222222222, ...","[0.0, 0.11088262850995298, 0.22039774345612226...",c,x**2,"[0.1, -1.0, 0.3, -1.0]","[-200, 20]",0.0,1,"[1.0, 5.0]",True,"[0.0, 1.0, 3.4]","[1.2, 3.1416, 3.141592653589793]","[1.0, 2.0, 1.3, 3.14]","[0, 1, 4, 20, 8]",0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20*y

In [6]:
fee_df2 = pd.read_parquet('../utils/.ans/Tema1/.__fee_1') # Se lee en un DataFrame
fee_df2

,1a,1b,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Deberías checar ...,None,Las opciones válidas son ...,Checa las reglas de derivación,Checa las entradas de la matriz A,Checa las entradas del vector B,Checa el valor de flotante,Checa el valor de entero,Checa el valor de complejo,Checa logico,Checa la lista,Checa la tupla,Checa la diccionario,Checa la conjunto,Revisa tus operaciones algebráicas para calcul...

# Evaluación de las respuestas

In [7]:
quizz.eval_numeric('1a', t)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [8]:
quizz.eval_numeric('1b', w)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [9]:
quizz.eval_option('2', 'c')

----------------------------------------
Tu respuesta: c, es correcta.
----------------------------------------

In [10]:
x = sy.Symbol('x')
resultado = x*x
display(resultado)

x**2

In [11]:
quizz.eval_expression('3', resultado)

----------------------------------------
Tu respuesta:

x**2

es correcta.
----------------------------------------

In [12]:
quizz.eval_numeric('4', matriz_np)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [13]:
quizz.eval_numeric('5', array_np)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [14]:
quizz.eval_numeric('6', flotante)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [15]:
quizz.eval_numeric('7', entero)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [16]:
quizz.eval_numeric('8', complejo)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [17]:
quizz.eval_numeric('9', logico)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [18]:
quizz.eval_numeric('10', lista)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [19]:
quizz.eval_numeric('11', tupla)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [20]:
quizz.eval_numeric('12', diccionario)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [21]:
quizz.eval_numeric('13', conjunto)

----------------------------------------
Tu resultado es correcto.
----------------------------------------

In [22]:
quizz.eval_expression('14', forma_cuadratica)

----------------------------------------
Tu respuesta:

0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20*y

es correcta.
----------------------------------------